#version 450

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

struct Buffer_t
{
    uint dspThrdId; //スレッドIDを書き込む 
};

layout(std430, binding = 0) buffer OutBuff
{
    uint data[];
};

void main()
{
    uvec3 dispatchThreadId = gl_GlobalInvocationID;

    // ただただIDを代入 
    uint index = dispatchThreadId.x * 4 * 4 + dispatchThreadId.y * 4 + dispatchThreadId.z;
    data[index] = index;
}