name: develop

on:
  push:
    branches: [ "develop" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
   
    # windowsでビルドする
    runs-on: windows-latest

    steps:
    - name: Clear git cache
      run: git gc --prune=all
    
    - uses: actions/checkout@v3.5.2
      with:
       submodules: 'recursive'
      
      # msbuildのセットアップ
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
      # ビルド
    - name: Build
      # Build your program with the given configuration
      run: |
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A x64
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
    - name: Tests
      run: | 
        cmake -DCMAKE_BUILD_TYPE=Debug -S ${{github.workspace}}/Test -B ${{github.workspace}}/Test/build
        cmake --build ${{github.workspace}}/Test/build --config ${{env.BUILD_TYPE}}
        
    - name: Run Tests
      run: ${{github.workspace}}/Test/build/Debug/tests --reporter junit --out ./result.xml
      
    - name: Show test results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      with:
        check_name: Catch2 tests
        path: ${{github.workspace}}/result.xml
      
      # アップロード
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyArtifact
        path: ${{github.workspace}}/${{env.BUILD_TYPE}}/EugeneLib.lib

      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyArtifact
        path: ./${{github.workspace}}/Relese
      
