name: develop

on:
  push:
    branches: [ "develop" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
   
    # windowsでビルドする
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
       submodules: 'recursive'
      
      # msbuildのセットアップ
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
      # ビルド
    - name: Build
      # Build your program with the given configuration
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A x64
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
      # アップロード
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyArtifact
        path: ${{github.workspace}}/Release/EugeneLib.lib

      
